### ISSUE TITLE
Fatal error - syntax error, unexpected '|', expecting variable (T_VARIABLE)  - when trying to add a user to a group

### ISSUE THREAD

**Issue by Adeline-44** [agorakit/agorakit#455]
Everything is in the title ;-)

PHP version 7.4.33
Agora version 1.7 (I know I'm not up to date, but I've got many troubles also with the update).

**Comment by philippejadin** [comment]
Can you add the informations about filename and line where the error occurs?
What problem did you got with the update?

Also, you might need a newer version of php.

**Comment by Adeline-44** [comment]
Here is the url : https://agora44.cdg44.fr/groups/4/invite
I only have

A fatal error occured
syntax error, unexpected '|', expecting variable (T_VARIABLE)
Contact the server admin to get help and explain what you were trying to do. Provide this error message to help fix the bug.

**Comment by Adeline-44** [comment]
About the update, after doing ./update, I've got the message 

Illuminate\Database\QueryException
SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES) (SQL: select * from `settings` where `name` = homepage_presentation limit 1) (View: /var/www/agorakit-1.7/resources/views/dashboard/presentation.blade.php)
https://agora44.cdg44.fr/

**Comment by linc** [comment]
@Adeline-44 This sort of error as a 1-off (others don't seem to be having this issue) seems most likely to come from a version mismatch between dependency libraries and your version of PHP. Did you happen to run `composer update` or update PHP lately? (I'm _not_ suggesting you do either.) AgoraKit 1.7 requires PHP `7.2.5` in Composer, but it's not specified as the platform for building dependencies. That means if you typed `composer update` it only confirms you have a valid of PHP, not that all the dependencies are actually compatible with it.

I would backup your database and then do a fresh install. I doubt this is going to get resolved as a GitHub issue because it's likely system-specific.
