### ISSUE TITLE
User table has required field 'body' which causes unit tests to fail

### ISSUE THREAD

**Issue by linc** [agorakit/agorakit#480]
PHPUnit currently returns errors like this:

```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: users.body in /home/runner/work/agorakit/agorakit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:501
```

```
Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: users.body (SQL: insert into "users" ("name", "email", "password", "username", "token", "admin", "updated_at", "created_at") values (Newbie, newbie@agorakit.org, $2y$10$JjLNulTkThR1NUS6VtK2d.OiEenFw8GQj8xgMJ91lSfMoMbHmZJG2, newbie, 4p2GFH8zEQSq6tLoW2RZyClto4gFuB, 1, 2024-08-25 01:28:30, 2024-08-25 01:28:30)) in /home/runner/work/agorakit/agorakit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
```

These appear to be the requirement that `users.body` be NOT NULL interfering with user insertions in the test setup that don't define a `body`.

The addition of that field requirement appears to trace to this commit, which doesn't explain the rationale: https://github.com/agorakit/agorakit/commit/ddcffb601fd031f2a87cac2a170e66485de57db6

What is the intended purpose of the `users.body` field? If this is intended as a "Bio" field, my sense is it should allow `NULL` as a value since that's not mission-critical. That seems like a better fix than amending the tests.

Blocks #465

**Comment by linc** [comment]
This blocks #465

**Comment by linc** [comment]
The addition of that field requirement appears to trace to this commit, which doesn't explain the rationale: https://github.com/agorakit/agorakit/commit/ddcffb601fd031f2a87cac2a170e66485de57db6

**Comment by linc** [comment]
If this is intended as a "Bio" field, my sense is it should allow `NULL` as a value since that's not mission-critical.

**Comment by philippejadin** [comment]
You are right users.body is intended as a bio fields. In order to simplify (?) things, I named all "primary" text field body (in discussions, comments, and actions they are there as well).
But it definitely should allow NULL, it's weird I did that.

Thank you for the very well linked and explained work btw. I'm taking notes for my learning :)

**Comment by philippejadin** [comment]
What is strange is that when I run `php artisan test`, all tests passes. At least using the docker wip dev setup located in /docker/franken

I think it is a sqlite vs mysql way of handling empty inserts in non nullable fields.
Here is an explanation : https://stackoverflow.com/a/74163240

Since supporting sqlite is part of the plan, it would be a good idea to create the needed migrations to properly "nullable" all the fields that need it.

There are pros and cons of doing the validation also in the models, at least I found  https://github.com/dwightwatson/validating very dependable with an easy to use syntax and models that do not get saved if not valid. I'm open to a better approach of course.

**Comment by linc** [comment]
Eventually, I think it would be great to validate in code and not rely on a database error. Today, I think we can just knock these out as we find them with migrations and take care with them as we add columns.
